service: sqs-lambda-example

custom:
  queueName: doTaskQueue

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        Fn::GetAtt: [ SQSQueue, Arn ]


functions:
  sensMessageSQS:
    handler: functions.sendMessageSQS.send
    environment:
      SQS_URL:
        Ref: SQSQueue
  doTask:
    handler: functions.doTask.do_task
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ SQSQueue, Arn ]

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}